replicaCount: 3

image:
  repository: vcut/microservices
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  grpcPort: 9090

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.vcut.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vcut-tls
      hosts:
        - api.vcut.example.com

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres"
    username: "vcut_user"
    password: "vcut_password"
    database: "vcut_db"

kafka:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
    size: 8Gi

redis:
  enabled: true
  auth:
    enabled: false
  persistence:
    enabled: true
    size: 8Gi