apiVersion: v1
kind: ConfigMap
metadata:
  name: vcut-config
  namespace: vcut-microservices
data:
  application.yml: |
    spring:
      profiles:
        active: production
      kafka:
        bootstrap-servers: kafka-cluster-kafka-bootstrap:9092
      r2dbc:
        url: r2dbc:postgresql://postgres-service:5432/vcut_db
        username: vcut_user
        password: ${DB_PASSWORD}
    storage:
      type: s3
      s3:
        endpoint: ${S3_ENDPOINT}
        region: ${S3_REGION}
        bucket-name: vcut-videos-prod
    grpc:
      server:
        port: 9090