apiVersion: v1
kind: Service
metadata:
  name: vcut-service
  namespace: vcut-microservices
spec:
  selector:
    app: vcut-microservices
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP