global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "vcut_rules.yml"

scrape_configs:
  - job_name: 'vcut-microservices'
    static_configs:
      - targets: ['vcut-service:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 5s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']